apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-of-anthos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/muzzammil-hamdu/bank-of-anthos.git
    targetRevision: main
    path: kubernetes-manifests

  destination:
    server: https://kubernetes.default.svc   # in-cluster — ArgoCD is on same aks-dev
    namespace: bank-of-anthos

  syncPolicy:
    automated:
      prune: true       # remove resources deleted from Git
      selfHeal: true    # revert any manual kubectl changes
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas    # ignore replica drift (e.g. from HPA)